# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Manash Kumar Mandal
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio of Manash Kumar Mandal
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mandal.manash.me"
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /aboutme.html

# Build settings
markdown: kramdown


